# Generated by Django 3.2.23 on 2024-01-13 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('danger_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_pic',
            field=models.ImageField(blank=True, upload_to='post_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='degree',
            field=models.IntegerField(choices=[(1, '10%'), (2, '20%'), (3, '30%'), (4, '40%'), (5, '50%'), (6, '60%'), (7, '70%'), (8, '80%'), (9, '90%'), (10, '100%')], default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='dt_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='hash',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='head',
            field=models.CharField(default='adfa', max_length=20),
            preserve_default=False,
        ),
    ]
